version: '3.2'

services:

  frontend:
    build: frontend
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend:
    build: backend
    links:
      - mysql
    ports:
      - 8081:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: secret

      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.1
    links:
      - mysql:mysql
    ports:
      - 8083:80
    environment:
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret